---
name: Compliance check with CloudFormation Guard
on:
  push
defaults:
  run:
      shell: bash
jobs:
  check-cfn-templates:
    name: Check AWS CloudFormation templates
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      
      - name: install CloudFormation Guard
          env: 
            CFN_GUARD_VERSION: 1.0.0
          run: |
            wget https://github.com/aws-cloudformation/cloudformation-guard/releases/download/${CFN_GUARD_VERSION}/cfn-guard-linux-${CFN_GUARD_VERSION}.tar.gz
            tar -xvf cfn-guard-linux-1.0.0.tar.gz

      - name: Deploy network stack
        uses: aws-actions/aws-cloudformation-github-deploy@master
        with:
          name: network
          template: templates/network.yml
          no-fail-on-empty-changeset: "1"

      - name: Deploy security group stack
        uses: aws-actions/aws-cloudformation-github-deploy@master
        with:
          name: sg
          template: templates/sg.yml
          no-fail-on-empty-changeset: "1"