---
name: Compliance check with CloudFormation Guard
on:
  push
defaults:
  run:
      shell: bash
jobs:
  check-cfn-templates:
    name: Check AWS CloudFormation templates
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: install CloudFormation Guard
        env: 
          CFN_GUARD_VERSION: 1.0.0
        run: |
          wget https://github.com/aws-cloudformation/cloudformation-guard/releases/download/${CFN_GUARD_VERSION}/cfn-guard-linux-${CFN_GUARD_VERSION}.tar.gz
          tar -xvf cfn-guard-linux-${CFN_GUARD_VERSION}.tar.gz

      - name: check network template with CloudFormation Guard
        env: 
          TEMPLATE: network
        run: |
          ./cfn-guard-linux/cfn-guard check --template ./templates/${TEMPLATE}.yml --rule_set ./cfn-guard-rules/${TEMPLATE}_ruleset

      - name: check security group template with CloudFormation Guard
        env: 
          TEMPLATE: sg
        run: |
          ./cfn-guard-linux/cfn-guard check --template ./templates/${TEMPLATE}.yml --rule_set ./cfn-guard-rules/${TEMPLATE}_ruleset

      - name: Deploy network stack
        env:
          STACK_NAME: network
        run: |
          aws cloudformation deploy \
            --stack-name ${STACK_NAME} \
            --template-file ./templates/${STACK_NAME}.yml \
            --no-fail-on-empty-changeset

      - name: Deploy security group stack
        env:
          STACK_NAME: sg
        run: |
          aws cloudformation deploy \
            --stack-name ${STACK_NAME} \
            --template-file ./templates/${STACK_NAME}.yml \
            --no-fail-on-empty-changeset